/// Flutter icons AirplaneEngineIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AirplaneEngineIcons
///      fonts:
///       - asset: assets/AirplaneEngineIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AirplaneEngineIcons {
  AirplaneEngineIcons._();

  static const _kFontFam = 'AirplaneEngineIcons';
  static const String? _kFontPkg = null;

  static const IconData jetengine1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jetengine2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData turbofanengineside2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData turbofanside = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData turbofanengineside3 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
